### ISSUE TITLE
[BUG] <title>drop frames 5.2.141-RC

### ISSUE THREAD

**Issue by mizone** [GoldpawsStuff/AzeriteUI5#55]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

drop frame during combat

### To reproduce

drop frame during combat
——>2 fps

### Additional context

drop frame during combat
——>2 fps

**Comment by Goldpaw** [comment]
There was a huge actionbutton taint bug in 5.2.141-RC, I fixed that in 5.2.142-RC today. 

If that's not the issue, I would assume the fps drop is a result of the other bug you reported: #56 

The other bug apparently fires at aura updates, and that can really drop the framerate as there are a LOT of them. But I need more info to fix it. See my comment on #56

**Comment by mizone** [comment]
I downloaded the files and replaced AzeriteUI in Addon, it reported a lot of errors. thus, i can not test the changes. Waiting for your offical update version for test, and then feedback.

**Comment by mizone** [comment]
when I use 5.2.137, no FPS drop issue. I think it related the content your updated in verison 5.2.141

**Comment by mizone** [comment]
5.2.142-RC, still show very bad performance, still drop FPS. fps drop to 5


![WoWScrnShot_121323_225627](https://github.com/GoldpawsStuff/AzeriteUI5/assets/13501972/c9c0002b-700e-497f-a45a-db4216ac5ae4)


below is a normal one, fps=57

![WoWScrnShot_121323_225339](https://github.com/GoldpawsStuff/AzeriteUI5/assets/13501972/79517682-875c-4709-afe5-e00f5b9559c0)

**Comment by mizone** [comment]
5.2.143 was tested. it still drop fps to around 20 in combat.

**Comment by Goldpaw** [comment]
It's probably the bug in #56 that's causing it. In a raid the event that's calling it fires a LOT, like possibly hundres of times a second. A bug there can cripple the UI. Fix coming today.

**Comment by mizone** [comment]
still drop frames. not smooth as the version 5.2.136, during combat. please check

**Comment by Goldpaw** [comment]
> much better, but still drop frames, not as smooth as the version 5.2.136, during combat. please check

A little hard for me to test since my laptop can only ever run the game around 35-55 frames per second, and that is always consistent. I don't have the hardware to check these things.
